Update randomexitcoderetry.yml

diff --git a/.github/workflows/randomexitcoderetry.yml b/.github/workflows/randomexitcoderetry.yml
--- a/.github/workflows/randomexitcoderetry.yml
+++ b/.github/workflows/randomexitcoderetry.yml
@@ -9,6 +9,8 @@ jobs:
     steps:
       - name: Retry sudo commands with random exit codes
         run: |
+          # Enable script to continue on errors
+          set +e
           # Define the maximum number of retries and delay between attempts
           MAX_RETRIES=5
           DELAY=10
@@ -19,7 +21,7 @@ jobs:
             echo "Simulating sudo command with exit code $RANDOM_EXIT_CODE"
             sudo apt-get update
             RANDOM_EXIT_CODE=$((RANDOM % 2))
-            sudo apt install firefox -y 
+            # sudo apt install firefox -y 
             python -m pip install --upgrade pip 
             pip install -r requirement.txt 
             sudo pip install html-testRunner
@@ -37,7 +39,9 @@ jobs:
           done
             # Print final status
           if [ $EXIT_CODE -ne 0 ]; then
-            echo "Command did not succeed after $MAX_RETRIES attempts, but the workflow will not fail."
+            echo "Command did not succeed after $MAX_RETRIES attempts"
+            set -e
+            exit 1
           else
             echo "Command succeeded!"
           fi
