Update retry_fordepencenies.yml

diff --git a/.github/workflows/retry_fordepencenies.yml b/.github/workflows/retry_fordepencenies.yml
--- a/.github/workflows/retry_fordepencenies.yml
+++ b/.github/workflows/retry_fordepencenies.yml
@@ -12,18 +12,36 @@ jobs:
     steps:
     - name: Checkout Code
       uses: actions/checkout@v3
-
+    - name: Simulate DNS Issue
+      run: echo "127.0.0.1 pypi.org" | sudo tee -a /etc/hosts
+      
     - name: Retry Setup Python
+      working-directory: ./opsjob/scripts
       run: |
-        # Retry logic with 3 attempts
-        for i in {1..3}; do
-          echo "Attempt $i to setup Python"
-          if python -m pip install --upgrade pip; then
-            echo "Python setup succeeded!"
-            break
-          elif [ $i -eq 3 ]; then
-            echo "Python setup failed after $i attempts. Exiting."
-            exit 1
-          fi
-          sleep 5
-        done
+          sudo add-apt-repository ppa:mozillateam/ppa -y
+          echo '
+          Package: *
+          Pin: release o=LP-PPA-mozillateam
+          Pin-Priority: 1001
+          ' | sudo tee /etc/apt/preferences.d/mozilla-firefox
+          echo 'Unattended-Upgrade::Allowed-Origins:: "LP-PPA-mozillateam:${distro_codename}";' | sudo tee /etc/apt/apt.conf.d/51unattended-upgrades-firefox
+          sudo apt-get update
+          sudo apt install firefox -y
+          cd apps/bff/src
+          for i in {1..3}; do
+            echo "Attempt $i to setup Python"
+            if python -m pip install --upgrade pip; then
+              echo "Python setup succeeded!"
+              break
+            elif [ $i -eq 3 ]; then
+              echo "Python setup failed after $i attempts. Exiting."
+              exit 1
+            fi
+            sleep 10
+          done
+          pip install -r ./e2e-test/requirement.txt
+          sudo pip install html-testRunner
+          python -m pip install -U selenium==4.12.0
+          
+    - name: Restore DNS Settings
+      run: sudo sed -i '/pypi.org/d' /etc/hosts
