Update testworkflow_dummyc.yml

diff --git a/.github/workflows/testworkflow_dummyc.yml b/.github/workflows/testworkflow_dummyc.yml
--- a/.github/workflows/testworkflow_dummyc.yml
+++ b/.github/workflows/testworkflow_dummyc.yml
@@ -12,13 +12,15 @@ jobs:
 
       - name: Run E2E Test Pre conditions
         id: pre-conditions
-          echo "This is E2E Test conditions"
-          exit 1 
+        run: |
+          echo "Run E2E Test Pre conditions"
+          exit 1  # Simulating failure
           
       - name: Run E2E Test
         id: main
-          echo "This is E2E Test"
-          exit 1 
+        run: |
+          echo "Run E2E Test"
+          exit 1  # Simulating failure
           
       - uses: actions/upload-artifact@v4
         if: ${{ steps.pre-conditions.conclusion == 'failure' }}
