test

diff --git a/.github/workflows/test-ssla-certs.yml b/.github/workflows/test-ssla-certs.yml
--- a/.github/workflows/test-ssla-certs.yml
+++ b/.github/workflows/test-ssla-certs.yml
@@ -43,29 +43,15 @@ jobs:
         # }
         # trap cleanup EXIT
         RUN_ID=$(gh run --repo ${OTHER_REPO} list --workflow ${WF_NAME} --json databaseId --jq .[1].databaseId) 
-        mkdir testresponse
-        cd testresponse
-        response=$(gh api \
-        -H "Accept: application/vnd.github+json" \
-        -H "X-GitHub-Api-Version: 2022-11-28" \
-        /repos/$OTHER_REPO/actions/runs/$RUN_ID)
-        url=$(echo $response | jq -r '.artifacts_url')
-        echo "url : $url"
-        echo "before" 
-        ls          
-        echo "url: $url"
-        echo "after"
-        res=$(curl -L \
-        -H "Accept: application/vnd.github+json" \
-        -H "Authorization: Bearer $GITHUB_TOKEN" \
-        -H "X-GitHub-Api-Version: 2022-11-28" \
-        $url)
-        count=$(echo $res | jq -r '.total_count')
-        if [[ $count == 0 ]] ; then
-          echo "$count"
-          else
-          echo "Count : $count"
-          fi
+        API_URL="https://api.github.com/repos/${OTHER_REPO}/actions/runs/${RUN_ID}/artifacts"
+        # Use curl to retrieve artifact information
+        response=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" $API_URL)
+        # Extract artifact ID based on the provided artifact name
+        artifact_id=$(echo "$response" | jq -r ".artifacts[] | select(.name == \"$ARTIFACT_NAME\") | .id")
+        if [ -z "$artifact_id" ]; then
+          echo "Artifact with name '$ARTIFACT_NAME' not found."
+          # exit 1
+        fi
         # gh run --repo ${OTHER_REPO} download ${RUN_ID} -n ${ARTIFACT_NAME} 
         filecount=$(ls | grep .csv -c)
         if [[  $filecount == 1 ]]; then 
